### ISSUE TITLE
Add optional arguments to actions

### ISSUE THREAD

**Issue by mstruebing** [nikkorn/mistreevous#27]
It would be great to have the option to add optional arguments to actions, that way it will be possible to write more generic actions.

definition:
```
root {
    sequence {
        action [DoPushUps 10]
    }
}
```

blackboard:

```js
const board = {
    DoPushUps: amount => {
        // do the actual pushups
        return State.SUCCEEDED;
    },
};
```

As I can see in the code you intentionally only allow an action name:

https://github.com/nikkorn/mistreevous/blob/master/src/rootASTNodesBuilder.js#L532-L538
```js
                // We should have only a single argument that is not an empty string for an action node, which is the action name.
                if (actionArguments.length === 1 && actionArguments[0] !== "") {
                    // The action name will be the first and only node argument.
                    node.actionName = actionArguments[0];
                } else {
                    throw "expected single action name argument";
                }
```

Do you think it makes sense to implement at all?
We could try to provide a pull request.

Have a good day
Max

**Comment by nikkorn** [comment]
I think having additional arguments for actions would be a great idea. If you wouldn't mind providing a PR that would be super. Thanks very much
