### ISSUE TITLE
TypeScript and "noImplicitAny: true" compiler error

### ISSUE THREAD

**Issue by blubberblah** [nikkorn/mistreevous#28]
Hi nikkorn,
in my TypeScript project i've set `noImplicitAny: true` in tsconfig.json

```
{
	"compilerOptions": {
        "module": "esNext",
	"target": "es5",
	"moduleResolution": "Node",
        "strict": true,
	"noImplicitAny": true, 
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "skipLibCheck": true,
	"preserveConstEnums":true,
        "sourceMap": true,
        "rootDir": "src",
    }
}
```
When importing mistreevous like follows in a TS souce file:
`import { BehaviourTree, State } from "../../node_modules/mistreevous/dist";`

I get following error:

```
ERROR in /home/vagrant/projects/bjs-testbed/src/enemyAi/EnemyBtMistreevous.ts
./src/enemyAi/EnemyBtMistreevous.ts
[tsl] ERROR in /home/vagrant/projects/bjs-testbed/src/enemyAi/EnemyBtMistreevous.ts(5,38)
      TS7016: Could not find a declaration file for module '../../node_modules/mistreevous/dist'. '/home/vagrant/projects/bjs-testbed/node_modules/mistreevous/dist/index.js' implicitly has an 'any' type.
```
When disabling this option e.g. `noImplicitAny: false` it compiles without any problems. Do you have an idea what to do to prevent this error when `noImplicitAny: true` ?

Thanks for this great libray :-)
Regards

**Comment by blubberblah** [comment]
Changing the module declaration in `mistreevous.d.ts` to lowercaase seems to fix the problem.
After changing 
```
declare module "Mistreevous" {
   // ...
}
```
to
```
declare module "mistreevous" {
   // ...
}
```
I can successfully import via `import { BehaviourTree, State } from "mistreevous";` Now the type definitions are recognized by the compiler and I can use `noImplicitAny: true`

Is it intentional that the modul declaration starts with an capital letter or a bug?

**Comment by nikkorn** [comment]
Thanks for taking the time to write up this issue. It looks like i whipped up the type declaration file without testing it out thoroughly enough. I think the module name should always have started with a lowercase letter to match the package name. I will make a fix for this at some point this week, Thanks again :)

**Comment by blubberblah** [comment]
Glad to help, thanks for fixing :-)
