### ISSUE TITLE
Accept JSON definitions

### ISSUE THREAD

**Issue by nikkorn** [nikkorn/mistreevous#52]

**Comment by bencoveney** [comment]
+1 - I think this would be a cool idea, and enable things like generating the tree programatically.

From looking through the code, I've seen that at the moment you have one chunk of logic that:
- Accepts the mistreevous code as input.
- Parses it into a graph structure.
- Evaluates the graph structure.

I think what you might want is to split that into 2 pieces.

The first piece (a compiler):
- Accepts the mistreevous code as input.
- Parses it into a JSON structure.

The second piece (an interpreter):
- Accepts the JSON structure as input.
- Evaluates the JSON structure.

That way people can opt to only use the second piece if they want to provide JSON. There might need to be a constraint that the JSON graph structure is clean enough that its not a pain to construct by hand.

I think at the moment there is a lot of state distributed amongst the different nodes in the graph structure what state they are in. Making a change like this might be easier if instead _the BehaviourTree interpreter held the state_ - for example a "pointer" to the currently running node.

The downside of doing that is that it would be tricky (but not impossible) to inspect the tree after running it, for example to render the visualisation. On the other hand I can think of a few upsides:
- Mistreevous could just "run" the JSON without having to transform it into classes first.
- You could also resume from (or jump to) arbitrary points within the tree and continue evaluation from there, without needing to worry about keeping all the node states correct.
- You could potentially also update/modify the tree _while it is running_, without needing to worry about keeping all the node states correct.

**Comment by nikkorn** [comment]
I really like the idea of splitting this out into two parts with always operating on JSON and converting a stringy definition to JSON as an optional first step. 

I also really like the idea of moving the state out of the graph and into an interperter. While i can understand how this might work in a situation where we are only tracking a single running node it gets a bit more complicated for:

- Multiple running nodes (due to parallel composite nodes).
- How we track which nodes have succeeded/failed, but it might be as easy as having a collection of failed and succeeded nodes in the interpreter (In production we don't really need to know about which nodes have failed/succeeded, but its needed for visualising the state of a running tree).
- Where we would move node-specific state, like the elapsed duration for a wait node?

Can you think of a good use case for modifying a behaviour tree while it is running? I like the concept but i cant put my finger on where it might be beneficial.

**Comment by mingfang** [comment]
Is there any progress on this.

I need to store the tree structure in a database and the structure can be changed while the tree is running.
I'm using behavior tree to model human workflow.
Traditionally that's a job for BPMN but I think behavior tree is a better fit.

**Comment by nikkorn** [comment]
@mingfang Hi, there has been a good amount of progress on this and I'm hoping to have this finished in the next few weeks.
