### ISSUE TITLE
error in a cocos game engine which is base typescript

### ISSUE THREAD

**Issue by VanHoth** [nikkorn/mistreevous#77]
<img width="691" alt="WeChat18962db711c327c4f0354d39a92950e6" src="https://github.com/nikkorn/mistreevous/assets/65997115/26f48d0f-da26-4cf3-8a8a-3e7fbad9d505">
<img width="517" alt="WeChat8b69b156a9239b5714c6fb6644edef8b" src="https://github.com/nikkorn/mistreevous/assets/65997115/62f23023-de04-4ba6-b96c-d04b8f979af9">

**Comment by VanHoth** [comment]
i have make it work
use rollup to export ESM,and set type 'module'

**Comment by nikkorn** [comment]
@VanHoth Sorry, i'm having a little trouble seeing what the error was, was it an actual issue with this library?
