### ISSUE TITLE
How to debug a tree

### ISSUE THREAD

**Issue by Welkin-Totoro** [nikkorn/mistreevous#78]
Any way to debug over step or visualize behaviour on a tree?

**Comment by nikkorn** [comment]
@Welkin-Totoro Hi, the only way to do this currently is to call getFlattenedNodeDetails() on the behaviour tree instance. This returns a flattened array of all of the nodes in the tree as well as their current state. This is what I've used to create the tree visualiser on the tree editor tool.

I do have an open issue (that I'm hoping to get to very soon) to address adding a debug callback to the options object which will be called every time a node changes state.

If you have any other suggestions about adding debugging I'd love to hear them.

Thanks
